export const subscribedEmails = [
  {
    id: "1",
    email: "juan.perez@gmail.com",
    name: "Juan Pérez",
    subscriptionDate: "2024-01-15",
    status: "active",
  },
  {
    id: "2",
    email: "maria.gonzalez@outlook.com",
    name: "María González",
    subscriptionDate: "2024-01-16",
    status: "active",
  },
  {
    id: "3",
    email: "carlos.rodriguez@yahoo.com",
    name: "Carlos Rodríguez",
    subscriptionDate: "2024-01-17",
    status: "active",
  },
  {
    id: "4",
    email: "ana.lopez@gmail.com",
    name: "Ana López",
    subscriptionDate: "2024-01-18",
    status: "active",
  },
  {
    id: "5",
    email: "pedro.martinez@hotmail.com",
    name: "Pedro Martínez",
    subscriptionDate: "2024-01-19",
    status: "active",
  },
  {
    id: "6",
    email: "laura.sanchez@gmail.com",
    name: "Laura Sánchez",
    subscriptionDate: "2024-01-20",
    status: "active",
  },
  {
    id: "7",
    email: "roberto.silva@outlook.com",
    name: "Roberto Silva",
    subscriptionDate: "2024-01-21",
    status: "active",
  },
  {
    id: "8",
    email: "sofia.herrera@gmail.com",
    name: "Sofia Herrera",
    subscriptionDate: "2024-01-22",
    status: "active",
  },
  {
    id: "9",
    email: "diego.morales@yahoo.com",
    name: "Diego Morales",
    subscriptionDate: "2024-01-23",
    status: "active",
  },
  {
    id: "10",
    email: "valentina.castro@gmail.com",
    name: "Valentina Castro",
    subscriptionDate: "2024-01-24",
    status: "active",
  },
  {
    id: "11",
    email: "andres.jimenez@hotmail.com",
    name: "Andrés Jiménez",
    subscriptionDate: "2024-01-25",
    status: "active",
  },
  {
    id: "12",
    email: "camila.vargas@gmail.com",
    name: "Camila Vargas",
    subscriptionDate: "2024-01-26",
    status: "active",
  },
  {
    id: "13",
    email: "felipe.ruiz@outlook.com",
    name: "Felipe Ruiz",
    subscriptionDate: "2024-01-27",
    status: "active",
  },
  {
    id: "14",
    email: "isabella.torres@gmail.com",
    name: "Isabella Torres",
    subscriptionDate: "2024-01-28",
    status: "active",
  },
  {
    id: "15",
    email: "sebastian.vega@yahoo.com",
    name: "Sebastián Vega",
    subscriptionDate: "2024-01-29",
    status: "active",
  },
  {
    id: "16",
    email: "natalia.mendoza@gmail.com",
    name: "Natalia Mendoza",
    subscriptionDate: "2024-01-30",
    status: "active",
  },
  {
    id: "17",
    email: "alejandro.pena@hotmail.com",
    name: "Alejandro Peña",
    subscriptionDate: "2024-01-31",
    status: "active",
  },
  {
    id: "18",
    email: "daniela.ortiz@gmail.com",
    name: "Daniela Ortiz",
    subscriptionDate: "2024-02-01",
    status: "active",
  },
  {
    id: "19",
    email: "mateo.guerrero@outlook.com",
    name: "Mateo Guerrero",
    subscriptionDate: "2024-02-02",
    status: "active",
  },
  {
    id: "20",
    email: "lucia.ramirez@gmail.com",
    name: "Lucía Ramírez",
    subscriptionDate: "2024-02-03",
    status: "active",
  },
];
